// Reference ranges in the style of the USMLE laboratory values table (conventional units).
export type LabRow = { name: string; range: string; si?: string };
export type LabSection = { key: string; title: string; rows: LabRow[] };

export const LAB_SECTIONS: LabSection[] = [
  {
    key: "serum",
    title: "Serum",
    rows: [
      { name: "Alanine aminotransferase (ALT)", range: "10–40 U/L" },
      { name: "Aspartate aminotransferase (AST)", range: "12–38 U/L" },
      { name: "Alkaline phosphatase", range: "25–100 U/L" },
      { name: "Amylase", range: "25–125 U/L" },
      { name: "Bilirubin, total // direct", range: "0.1–1.0 mg/dL // 0.0–0.3 mg/dL" },
      { name: "Calcium", range: "8.4–10.2 mg/dL" },
      { name: "Cholesterol, total", range: "Normal: <200 mg/dL; High: >240 mg/dL" },
      { name: "Cholesterol, HDL // LDL", range: "40–60 mg/dL // <160 mg/dL" },
      { name: "Triglycerides", range: "Normal: <150 mg/dL" },
      { name: "Cortisol", range: "0800 h: 5–23 μg/dL; 1600 h: 3–15 μg/dL" },
      { name: "Creatine kinase", range: "Male: 25–90 U/L; Female: 10–70 U/L" },
      { name: "Creatinine", range: "0.6–1.2 mg/dL" },
      { name: "Sodium (Na⁺)", range: "136–146 mEq/L" },
      { name: "Potassium (K⁺)", range: "3.5–5.0 mEq/L" },
      { name: "Chloride (Cl⁻)", range: "95–105 mEq/L" },
      { name: "Bicarbonate (HCO₃⁻)", range: "22–28 mEq/L" },
      { name: "Magnesium (Mg²⁺)", range: "1.5–2.0 mg/dL" },
      { name: "Phosphorus (inorganic)", range: "3.0–4.5 mg/dL" },
      { name: "Ferritin", range: "Male: 20–250 ng/mL; Female: 10–120 ng/mL" },
      { name: "Iron", range: "Male: 65–175 μg/dL; Female: 50–170 μg/dL" },
      { name: "Total iron-binding capacity", range: "250–400 μg/dL" },
      { name: "Transferrin", range: "200–360 mg/dL" },
      { name: "Follicle-stimulating hormone", range: "Male: 4–25 mIU/mL; Female premenopause: 4–30 mIU/mL; midcycle peak: 10–90 mIU/mL; postmenopause: 40–250 mIU/mL" },
      { name: "Luteinizing hormone", range: "Male: 6–23 mIU/mL; Female follicular: 5–30 mIU/mL; midcycle: 75–150 mIU/mL; postmenopause: 30–200 mIU/mL" },
      { name: "Glucose", range: "Fasting: 70–100 mg/dL" },
      { name: "Lactate dehydrogenase", range: "45–200 U/L" },
      { name: "Lipase", range: "13–60 U/L" },
      { name: "Osmolality", range: "275–295 mOsmol/kg H₂O" },
      { name: "Parathyroid hormone, intact", range: "10–65 pg/mL" },
      { name: "Prolactin", range: "Male: <17 ng/mL; Female: <25 ng/mL" },
      { name: "Proteins, total", range: "6.0–7.8 g/dL" },
      { name: "Albumin", range: "3.5–5.5 g/dL" },
      { name: "Globulin", range: "2.3–3.5 g/dL" },
      { name: "Thyroid-stimulating hormone", range: "0.4–4.0 μU/mL" },
      { name: "Thyroxine (T₄), total // free", range: "5–12 μg/dL // 0.9–1.7 ng/dL" },
      { name: "Triiodothyronine (T₃)", range: "100–200 ng/dL" },
      { name: "Troponin I", range: "≤0.04 ng/mL" },
      { name: "Urea nitrogen", range: "7–18 mg/dL" },
      { name: "Uric acid", range: "3.0–8.2 mg/dL" },
      { name: "Immunoglobulin A // E", range: "76–390 mg/dL // 0–380 IU/mL" },
      { name: "Immunoglobulin G // M", range: "650–1500 mg/dL // 50–300 mg/dL" },
    ],
  },
  {
    key: "abg",
    title: "Blood gases",
    rows: [
      { name: "pH", range: "7.35–7.45" },
      { name: "Pco₂", range: "33–45 mm Hg" },
      { name: "Po₂", range: "75–105 mm Hg" },
      { name: "HCO₃⁻", range: "22–28 mEq/L" },
    ],
  },
  {
    key: "heme",
    title: "Hematology",
    rows: [
      { name: "Erythrocyte count", range: "Male: 4.3–5.9 million/mm³; Female: 3.5–5.5 million/mm³" },
      { name: "Erythrocyte sedimentation rate (Westergren)", range: "Male: 0–15 mm/h; Female: 0–20 mm/h" },
      { name: "Hematocrit", range: "Male: 41%–53%; Female: 36%–46%" },
      { name: "Hemoglobin", range: "Male: 13.5–17.5 g/dL; Female: 12.0–16.0 g/dL" },
      { name: "Hemoglobin A1c", range: "≤6%" },
      { name: "Leukocyte count", range: "4500–11,000/mm³" },
      { name: "Neutrophils, segmented // bands", range: "54%–62% // 3%–5%" },
      { name: "Lymphocytes // monocytes", range: "25%–33% // 3%–7%" },
      { name: "Eosinophils // basophils", range: "1%–3% // 0%–0.75%" },
      { name: "CD4⁺ T-lymphocyte count", range: "≥500/mm³" },
      { name: "Platelet count", range: "150,000–400,000/mm³" },
      { name: "Reticulocyte count", range: "0.5%–1.5%" },
      { name: "Mean corpuscular volume", range: "80–100 μm³" },
      { name: "Mean corpuscular hemoglobin", range: "25–35 pg/cell" },
      { name: "Mean corpuscular hemoglobin concentration", range: "31%–36% Hb/cell" },
      { name: "Prothrombin time", range: "11–15 s" },
      { name: "Partial thromboplastin time (activated)", range: "25–40 s" },
      { name: "D-dimer", range: "≤250 ng/mL" },
      { name: "Fibrinogen", range: "200–400 mg/dL" },
      { name: "Bleeding time", range: "2–7 min" },
    ],
  },
  {
    key: "csf",
    title: "Cerebrospinal fluid",
    rows: [
      { name: "Cell count", range: "0–5/mm³" },
      { name: "Chloride", range: "118–132 mEq/L" },
      { name: "Gamma globulin", range: "3%–12% total proteins" },
      { name: "Glucose", range: "40–70 mg/dL" },
      { name: "Pressure", range: "70–180 mm H₂O" },
      { name: "Proteins, total", range: "<40 mg/dL" },
    ],
  },
  {
    key: "urine",
    title: "Urine and other",
    rows: [
      { name: "Calcium", range: "100–300 mg/24 h" },
      { name: "Creatinine clearance", range: "Male: 97–137 mL/min; Female: 88–128 mL/min" },
      { name: "Osmolality", range: "50–1200 mOsmol/kg H₂O" },
      { name: "Oxalate", range: "8–40 μg/mL" },
      { name: "Potassium", range: "25–125 mEq/24 h" },
      { name: "Proteins, total", range: "<150 mg/24 h" },
      { name: "Sodium", range: "40–220 mEq/24 h" },
      { name: "Uric acid", range: "240–600 mg/24 h" },
      { name: "Sweat chloride", range: "0–35 mmol/L" },
      { name: "Body mass index (adult)", range: "19–25 kg/m²" },
    ],
  },
];
